<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: search.proto

namespace GPBMetadata;

class Search
{
    public static $is_initialized = false;

    public static function initOnce() {
        $pool = \Google\Protobuf\Internal\DescriptorPool::getGeneratedPool();

        if (static::$is_initialized == true) {
          return;
        }
        $pool->internalAddGeneratedFile(hex2bin(
            "0a640a0c7365617263682e70726f746f224c0a0d53656172636852657175" .
            "657374120d0a05717565727918012001280912130a0b706167655f6e756d" .
            "62657218022001280512170a0f726573756c745f7065725f706167651803" .
            "20012805620670726f746f33"
        ));

        static::$is_initialized = true;
    }
}

